language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - python setup.py install
  - pip install pytest-cov
script: py.test --cov=django_prices_vatlayer

env:
  global:
    - DATABASE_URL='postgres://postgres@localhost:5432/django-prices-vatlayer'

services:
  - postgresql
addons:
  postgresql: "9.5"