language: python
python:
  - 2.7
  - 3.4
  - 3.5
install:
  - python setup.py install
  - pip install pytest-cov
script: py.test

env:
  global:
    - DATABASE_URL='postgres://postgres@localhost:5432/settings'

services:
  - postgresql
addons:
  postgresql: "9.4"